name: Build python wheel macos
description: Build and upload wheel for a specific python version on macos
inputs:
  version:
    description: Python version
    required: true
  arch:
    description: Architecture
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}

    - run: ./scripts/github-actions/macos/build-hext-python-macos.sh ${{ env.pythonLocation }}
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: hext-python${{ inputs.version }}-macos-${{ inputs.arch }}-${{ github.sha }}
        path: ${{ env.WHEEL_OUT }}

    - run: rm -rf ${{ env.WHEEL_OUT }}/*
      shell: bash
