INCLUDE(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CPP11)
IF(COMPILER_SUPPORTS_CPP11)
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
ELSE(COMPILER_SUPPORTS_CPP11)
  MESSAGE(STATUS "${CMAKE_CXX_COMPILER} does not support the flag -std=c++11.")
  MESSAGE(STATUS "C++11 is required.")
ENDIF(COMPILER_SUPPORTS_CPP11)

