IF(NOT HEXT_VERSION_FILE_SOURCE)
  MESSAGE(FATAL_ERROR "HEXT_VERSION_FILE_SOURCE not set. Cannot generate version file.")
ELSE(NOT HEXT_VERSION_FILE_SOURCE)
  # Note: GET_FILENAME_COMPONENT cannot be used here, it strips all extensions.
  STRING(REGEX REPLACE ".in$" "" HEXT_VERSION_FILE_TARGET ${HEXT_VERSION_FILE_SOURCE})

  CONFIGURE_FILE(
    ${HEXT_VERSION_FILE_SOURCE}
    ${HEXT_VERSION_FILE_TARGET}
    @ONLY)
ENDIF(NOT HEXT_VERSION_FILE_SOURCE)

