INCLUDE(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CPP14)
IF(COMPILER_SUPPORTS_CPP14)
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
ELSE(COMPILER_SUPPORTS_CPP14)
  MESSAGE(STATUS "${CMAKE_CXX_COMPILER} does not support the flag -std=c++14.")
  MESSAGE(STATUS "C++14 is required.")
ENDIF(COMPILER_SUPPORTS_CPP14)

