name: Test node modules and python wheels for macos
runs:
  using: composite
  steps:
    - name: Test python${{ env.HEXT_PYTHON_VERSION1 }} wheel
      uses: ./.github/actions/test-hext-python-macos-version
      with:
        version: ${{ env.HEXT_PYTHON_VERSION1 }}
        arch: ${{ env.HEXT_ARCH }}

    - name: Test python${{ env.HEXT_PYTHON_VERSION2 }} wheel
      uses: ./.github/actions/test-hext-python-macos-version
      with:
        version: ${{ env.HEXT_PYTHON_VERSION2 }}
        arch: ${{ env.HEXT_ARCH }}

    - name: Test python${{ env.HEXT_PYTHON_VERSION3 }} wheel
      uses: ./.github/actions/test-hext-python-macos-version
      with:
        version: ${{ env.HEXT_PYTHON_VERSION3 }}
        arch: ${{ env.HEXT_ARCH }}

    - name: Test python${{ env.HEXT_PYTHON_VERSION4 }} wheel
      uses: ./.github/actions/test-hext-python-macos-version
      with:
        version: ${{ env.HEXT_PYTHON_VERSION4 }}
        arch: ${{ env.HEXT_ARCH }}

    - name: Test python${{ env.HEXT_PYTHON_VERSION5 }} wheel
      uses: ./.github/actions/test-hext-python-macos-version
      with:
        version: ${{ env.HEXT_PYTHON_VERSION5 }}
        arch: ${{ env.HEXT_ARCH }}

    - uses: ./.github/actions/test-hext-npm
