name: Hext Releases for Linux
on: [push]

jobs:
  python_releases:
    name: Python releases
    runs-on: ubuntu-latest
    container:
      image: thomastrapp/static-build-env
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: "Build"
      run: |
        bash $GITHUB_WORKSPACE/scripts/build-hext-python/build-hext-python.sh
    - uses: actions/upload-artifact@v1
      with:
        name: python-releases
        path: scripts/build-hext-python/output
  node_releases:
    name: Node releases
    runs-on: ubuntu-latest
    container:
      image: thomastrapp/static-build-env-jessie
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: "Build"
      run: |
        bash $GITHUB_WORKSPACE/scripts/build-hext-npm/build-hextjs-linux.sh
        "bash $GITHUB_WORKSPACE/scripts/build-hext-npm/bundle-hextjs-npm-package.sh
          $GITHUB_WORKSPACE/scripts/build-hext-npm/package
          $GITHUB_WORKSPACE/scripts/build-hext-npm/output/*node"
    - uses: actions/upload-artifact@v1
      with:
        name: node-releases
        path: scripts/build-hext-npm/package
  python_test:
    name: Python test
    needs: python_releases
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux1_x86_64
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/download-artifact@v1
      with:
        name: python-releases
        path: scripts/python-pip-test/wheels
    - name: "Test"
      run: |
        bash $GITHUB_WORKSPACE/scripts/python-pip-test/python-pip-test.sh
