name: Hext Releases for Linux
on: [push]

jobs:
  python_releases:
    name: Python
    runs-on: ubuntu-latest
    container:
      image: thomastrapp/static-build-env
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: "Build"
      run: bash $GITHUB_WORKSPACE/scripts/build-hext-python/build-hext-python.sh
    - uses: actions/upload-artifact@v1
      with:
        name: python-wheels
        path: scripts/build-hext-python/output
    - uses: actions/upload-artifact@v1
      with:
        name: htmlext-static-binary-x86_64
        file: /usr/local/bin/htmlext
  node_releases:
    name: Node
    runs-on: ubuntu-latest
    container:
      image: thomastrapp/static-build-env-jessie
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: bash $GITHUB_WORKSPACE/scripts/build-hext-npm/build-hextjs-linux.sh
    - name: Bundle
      run: >
        bash $GITHUB_WORKSPACE/scripts/build-hext-npm/bundle-hextjs-npm-package.sh
        $GITHUB_WORKSPACE/scripts/build-hext-npm/package
        $GITHUB_WORKSPACE/scripts/build-hext-npm/output/*node
    - uses: actions/upload-artifact@v1
      with:
        name: npm-package
        path: scripts/build-hext-npm/package
  python_test:
    name: Python Test
    needs: python_releases
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux1_x86_64
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/download-artifact@v1
      with:
        name: python-wheels
        path: scripts/python-pip-test/wheels
    - name: Pip install and test
      run: bash $GITHUB_WORKSPACE/scripts/python-pip-test/python-pip-test.sh
  node_test:
    needs: node_releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '8', '10', '11', '12' ]
    name: Node v${{ matrix.node }} Test
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/download-artifact@v1
      with:
        name: node-package
        path: rls
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Run tests
      shell: bash
      run: >
        node --version
        && cd $GITHUB_WORKSPACE/test
        && npm install ../rls
        && cp ../libhext/bindings/nodejs/htmlext.js .
        && HTMLEXT="node htmlext.js" ./blackbox.sh case/*hext
