name: Hext CI
on: [push, pull_request]

jobs:
  hext_ci:
    name: Hext CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: ./scripts/github-actions/ci/hext-ci.sh

